### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by whippingdot** [Repl-it-Coders/Racer#1]
Hey, in the python team where we had our discussion there is also a tab called repos. Create/transfer your repo over there.

**Comment by BD103** [comment]
We can't do that. Only the mods / owners can. :(

**Comment by whippingdot** [comment]
No you can, I am pretty sure @firefish111 did that. What can't you do? Create a repo in a team, or transfer a repo, or what

**Comment by BD103** [comment]
![Screenshot 2021-01-07 at 08 48 48](https://user-images.githubusercontent.com/59022059/103899956-32715680-50c5-11eb-90b0-56cafe853df0.png)

**Comment by whippingdot** [comment]
> ![Screenshot 2021-01-07 at 08 48 48](https://user-images.githubusercontent.com/59022059/103899956-32715680-50c5-11eb-90b0-56cafe853df0.png)
> 
> Should i be seeing something here?

Yup, you should be seeing a create repo button or something. @firefish111 is a mod in the teams(cause he has mod permissions I gave him) so that must be why he can create repos. I will create a repo for you, one sec...

**Comment by BD103** [comment]
Can you make me a mod for @Repl-it-Coders/python @whippingdot

**Comment by ColePete** [comment]
me too? Since I code mostly with python.

**Comment by whippingdot** [comment]
@BD103 it is called maintainer and yes and @ColePete I can't make everyone a maintainer. Sorry. In the future maybe. There are already 2 maintainers for the python team and I think that is enough

**Comment by ColePete** [comment]
ouch... ok

**Comment by whippingdot** [comment]
Sorry

**Comment by ColePete** [comment]
all good, was just joking

**Comment by BD103** [comment]
@whippingdot https://github.com/Repl-it-Coders/Community-Discussion/discussions/8

**Comment by whippingdot** [comment]
I commented on it

**Comment by cursorweb** [comment]
hello, world

**Comment by ColePete** [comment]
?

**Comment by whippingdot** [comment]
?? @cursorweb. You finally responded to something btw. You SOO silent. Can you pls help with the projects ~~and don't just make our project "depend" on your project~~

**Comment by BD103** [comment]
I'm going to close this issue now, because we are obviously heading off topic.

_Though, @whippingdot, I still can't add / remove / edit repos in team python_

**Comment by ColePete** [comment]
lol

**Comment by whippingdot** [comment]
> I'm going to close this issue now, because we are obviously heading off topic.
> 
> _Though, @whippingdot, I still can't add / remove / edit repos in team python_

I haven't done it yet, will do rn

**Comment by BD103** [comment]
Ok. Closing issue.

(Next time we discuss something, can we please do it in the discussions tab? Thanks....)
